#
# Copyright (c) Sebastian Kucharczyk <kuchen@kekse.biz>
# https://kekse.biz/ https://github.com/kekse1/
#
# see also https://github.com/yt-dlp/yt-dlp/
#

# speicherort fuer alle files
-o "~/YouTube/download/[%(id)s] %(title)s]/[%(id)s] %(title)s.%(ext)s"
# symlinks zur einzelnen (merged) datei woanders sammeln
# bedenke: zuerst das ziel-verzeichnis erzeugen!!!
--exec="ln -srf {} ~/YouTube/files/"

# best quality
-f bv*+ba/b
--merge-output-format mkv
--video-multistreams
--audio-multistreams
--prefer-free-formats
#??
--check-formats
--check-all-formats

# metadaten und kapitel einbetten
--embed-thumbnail
--embed-metadata
--embed-chapters
--embed-subs
--sub-langs de,en

# progress bar..
--progress
#--print-traffic

# ...
--live-from-start
--download-archive ~/YouTube/archive
--break-on-existing

# really?
--no-playlist

#
--no-restrict-filenames
--trim-filenames 192
--continue

--write-thumbnail
--write-all-thumbnails
--write-description
--write-info-json
--write-playlist-metafiles
--no-clean-info-json
--write-subs
--write-auto-subs

#???
--write-comments

#
--cache-dir ~/YouTube/cache/

# got premium?
#--cookies-from-browser firefox
#--cookies-from-browser chrome
#--js-runtimes node
#--js-runtimes "node:/usr/bin/node"

